### ISSUE TITLE
can't retrieve entity config magento

### ISSUE THREAD

**Issue by smk2002** [outeredge/edge-magento-module-productrestrictshipping#1]
I try to install in my magento 1.9.2, i got below error..

a:5:{i:0;s:232:"Error in file: "/magento/app/code/local/Edge/ProductRestrictShipping/sql/productrestrictshipping_setup/mysql4-install-1.0.0.php" - Can't retrieve entity config: productrestrictshipping/productrestrictshipping";i:1;s:1012:"#0 /magento/app/code/core/Mage/Core/Model/Resource/Setup.php(645): Mage::exception('Mage_Core', 'Error in file: ...')

**Comment by broopdias** [comment]
Hi

Thank you for create a ticket for this.
Fix for this issue is in my last commit.

Cheers,
Bruno Dias

**Comment by smk2002** [comment]
First, I try to create New Attributs "productrestrict" with text fields And then do and chose setting at Configuration,  After that, i got to Porduct Restrict Shipping Under Catalog Menu.

1) so i create Add New Under Product Restrict Shipping. i got below error..
Fatal error: Can't use function return value in write context in /app/code/local/Edge/ProductRestrictShipping/Block/Adminhtml/Restrict/Edit/Form.php on line 16

So, i re-upload old file, i can create like that
First, Choose Country "SG" and select Attribute "productrestrict", Second, Choose Country "JP" and select Attribute "productrestrict"

2) We're using one page checkout extension ( https://www.iwdagency.com/extensions/one-step-page-checkout.html ). After checkout, still showing loading. so i check in console in chrome. I got below error
Failed to load resource: the server responded with a status of 500 (Internal Server Error) https://www.domain.com/magento/onepage/json/saveBilling 

Please let me know how to solve it.

**Comment by davidwindell** [comment]
What errors are showing in your PHP/Magento logs?

**Comment by smk2002** [comment]
Here my exception file > http://s000.tinyupload.com/?file_id=00394813009468189080

for Console in Chrome is show > 

> POST /onepage/json/reloadShippingsPayments 500 (Internal Server Error)
> POST /magento/onepage/json/saveBilling 500 (Internal Server Error)

**Comment by broopdias** [comment]
I'm working on it
I let you know when I find a solution

2015-10-20 10:45 GMT+01:00 smk2002 notifications@github.com:

**Comment by broopdias** [comment]
Tested on two magento projects with default checkout, and no problems detected.
You provably need to do some changes on your opcheckou.js file because is custom for checkout extension you are using. Take a look at sendAjaxRequest function and catch the fail response and then redirect to checkout/cart page.
Something like this:

sendAjaxRequest: function() {
...

this.xhr = jQuery.ajax({
       type: "POST",
       url: jQuery(this.options.form).attr('action'),
       data: data,
       dataType: 'json'
})
.done(this.nextStep)
.fail(function(response){
       window.location.href = '/checkout/cart';
});
}

**Comment by smk2002** [comment]
Did you mean "opcheckout.js" file is original magento (v1.9.2) file?

I can't find sendAjaxRequest fuction in opcheckout.js and my third party checkout.js file.

Here my third party js files => http://s000.tinyupload.com/?file_id=30001288019335135578

If you don't mind, pls let me know it. thanks

**Comment by broopdias** [comment]
Take a look at your saveShippingMethod function.
You need to check if the ajax response is failing on saving the shipping method, if yes, you need to redirect to checkout/cart
Maybe something like this (not tested)
if (IWD.OPC.Checkout.ajaxProgress == false){
window.location.href = '/checkout/cart';
}
